[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Передача переменных окружения в build
[[build.buildArgs]]
name = "DATABASE_URL"
value = "${{Postgres.DATABASE_URL}}"

[[build.buildArgs]]
name = "REDIS_URL"
value = "${{Redis.REDIS_URL}}"


