[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "chmod +x scripts/start-with-migrations.sh && ./scripts/start-with-migrations.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10



# Auto-deploy test
# Railway webhook test 1760023102
