[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Передача переменных окружения в build (публичные адреса для build time)
[[build.buildArgs]]
name = "DATABASE_URL"
value = "postgresql://postgres:AEXabgipqvhbLSwunyuZfLBgwtZsgHjg@hopper.proxy.rlwy.net:40277/railway"

[[build.buildArgs]]
name = "REDIS_URL"
value = "redis://default:VwgtfvXFMAnuMOItGfwKMSZSWODgwVVs@turntable.proxy.rlwy.net:27179"


